dense1:
  _target_: torch.nn.Linear
  in_features: 9216
  out_features: 100

drop1:
  _target_: torch.nn.Dropout
  p: 0.5

dense2:
  _target_: torch.nn.Linear
  in_features: ${classifier.dense1.out_features}
  out_features: 100

drop2:
  _target_: torch.nn.Dropout
  p: 0.5

dense3:
  _target_: torch.nn.Linear
  in_features: ${classifier.dense1.out_features}
  out_features: ${dataset.classes}