research_task:
  description: >
    Conduct a thorough research about {topic}
    Make sure you find any interesting and relevant information given
    the current year is 2024.
  expected_output: >
    A list with 5 bullet points of the most relevant information about {topic}

reporting_task:
  description: >
    Review the context you got and expand each topic into a full section for a report.
    Make sure the report is detailed and contains any and all relevant information.
  expected_output: >
    A fully fledge reports with the mains topics, each with a full section of information.
    Formated as markdown with out '```'

translate_task:
  description: >
    Translate the information to Brazilian Portuguese
  expected_output: >
    A fully translated report in Brazilian Portuguese
    Formated as markdown with out '```'